### PR TITLE
Batch upload for organisation admin

### PR DESCRIPTION
**Pull request by dwhenry**
Get Batch upload working for organisational admin.

I will look to add some testing around this fix so that it can be cherry-picked into master later this week if I have time.

### CODE REVIEW

**Comment by benlovell** [comment]
Nicely done. Although I think this should start with a failing test, regardless of our intentions to upstream the changes here.

**Comment by dwhenry** [comment]
@benlovell you want to give this a once over, then once I have merged locally I will cherry-pick onto master.

**Comment by benlovell** [comment]
@dwhenry Tests are failing on travis. Seems like a weird encoding issue somewhere. Can we address that first and I'll review after.

**Comment by benbarnett** [comment]
Ah ha, that did it!

**Pull request merged**
